import { Constants } from "@types";

export const TYPES: Constants = {
  ADD_TO_FAVORITES: "ADD_TO_FAVORITES",
  REMOVE_FROM_FAVORITES: "REMOVE_FROM_FAVORITES",
  REMOVE_ALL_FROM_FAVORITES: "REMOVE_ALL_FROM_FAVORITES",
  CHANGE_API: "CHANGE_API",
};
